# Generated by Django 3.1 on 2020-08-21 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GraphicDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('filter_by', models.CharField(choices=[('Vector', 'Vector'), ('Art', 'Art'), ('Designs', 'Designs'), ('Photo Manipulation', 'Photo Manipulation')], max_length=100)),
                ('img', models.ImageField(upload_to='graphic_design')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('template', models.FileField(blank=True, null=True, upload_to='graphic_design/zip_files')),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('free', models.BooleanField()),
                ('downloads', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LightroomPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('old_img', models.ImageField(upload_to='lightroom')),
                ('new_img', models.ImageField(upload_to='lightroom')),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('free', models.BooleanField()),
                ('preset_file', models.FileField(upload_to='lightroom/preset')),
                ('downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LightroomPresetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(default='featured_image/default.jpg', upload_to='featured_image')),
            ],
            options={
                'verbose_name_plural': 'Lightroom preset catergories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.coupon')),
                ('lightroom_items', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lightroom_items', to='shop.lightroompreset')),
                ('photoshop_items', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='photoshop_items', to='shop.graphicdesign')),
            ],
        ),
        migrations.AddField(
            model_name='lightroompreset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightroom_category', to='shop.lightroompresetcategory'),
        ),
        migrations.AddField(
            model_name='lightroompreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LightroomPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.lightroompresetcategory')),
                ('presets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.lightroompreset')),
            ],
        ),
    ]
