# Generated by Django 3.1 on 2020-08-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightroompreset',
            name='slug',
            field=models.SlugField(default='test-test', max_length=200),
            preserve_default=False,
        ),
    ]
