# Generated by Django 3.1 on 2020-08-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_lightroompreset_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightroompreset',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
